// Auto-generated by packages/cli/locale — do not edit manually
// Run `bun run validate:schema` to regenerate from locales/ directory.

export type Locale =
  | "ar-SA"
  | "bn-BD"
  | "de-DE"
  | "en-US"
  | "es-ES"
  | "fr-FR"
  | "hi-IN"
  | "id-ID"
  | "it-IT"
  | "ja-JP"
  | "ko-KR"
  | "nl-NL"
  | "pl-PL"
  | "pt-BR"
  | "ro-RO"
  | "ru-RU"
  | "th-TH"
  | "tr-TR"
  | "uk-UA"
  | "vi-VN"
  | "zh-CN";
