import fs from "node:fs";
import path from "node:path";
import { getLocaleFiles } from "./get-files";
import { LocaleFileSchema } from "./schema";

export const generate = (repoRoot: string): void => {
  const schema = LocaleFileSchema.toJSONSchema();
  const schemaPath = path.resolve(repoRoot, "locale-schema.json");
  fs.writeFileSync(schemaPath, `${JSON.stringify(schema, null, 2)}\n`);
  console.error(`Generated ${schemaPath}`);

  const files = getLocaleFiles(repoRoot);
  const codes = files.map((f) => path.basename(f, ".json"));
  const union = codes.map((c) => `  | "${c}"`).join("\n");
  const content = `// Auto-generated by packages/cli/locale — do not edit manually
// Run \`bun run validate:schema\` to regenerate from locales/ directory.

export type Locale =
${union};
`;

  const typePath = path.resolve(repoRoot, "packages/locales/src/types/locale.ts");
  fs.writeFileSync(typePath, content);
  console.error(`Generated ${typePath} (${codes.length} locales)`);
};
