import fs from "node:fs";
import path from "node:path";
import { LocaleFileSchema } from "@agents-radar/core";
import Ajv from "ajv/dist/2020";

export interface LocaleActionArgs {
  generate?: boolean;
  validate?: boolean;
}

export type LocaleActionDeps = {
  repoRoot?: string;
};

const getLocaleFiles = (repoRoot: string): string[] =>
  fs
    .readdirSync(path.resolve(repoRoot, "locales"))
    .filter((f) => f.endsWith(".json"))
    .sort();

const doGenerate = (repoRoot: string): void => {
  const schema = LocaleFileSchema.toJSONSchema();
  const schemaPath = path.resolve(repoRoot, "locale-schema.json");
  fs.writeFileSync(schemaPath, `${JSON.stringify(schema, null, 2)}\n`);
  console.error(`Generated ${schemaPath}`);

  const files = getLocaleFiles(repoRoot);
  const codes = files.map((f) => path.basename(f, ".json"));
  const union = codes.map((c) => `  | "${c}"`).join("\n");
  const content = `// Auto-generated by packages/cli/locale — do not edit manually
// Run \`bun run validate:schema\` to regenerate from locales/ directory.

export type Locale =
${union};
`;

  const typePath = path.resolve(repoRoot, "packages/core/src/types/locale.ts");
  fs.writeFileSync(typePath, content);
  console.error(`Generated ${typePath} (${codes.length} locales)`);
};

const doValidate = (repoRoot: string): boolean => {
  const schemaPath = path.resolve(repoRoot, "locale-schema.json");
  const schema = JSON.parse(fs.readFileSync(schemaPath, "utf-8"));

  const ajv = new Ajv();
  const validate = ajv.compile(schema);

  let allValid = true;
  for (const file of getLocaleFiles(repoRoot)) {
    const data = JSON.parse(fs.readFileSync(path.resolve(repoRoot, "locales", file), "utf-8"));
    if (!validate(data)) {
      console.error(`${file}:`, JSON.stringify(validate.errors, null, 2));
      allValid = false;
    }
  }

  return allValid;
};

export const localeAction = async (args: LocaleActionArgs, deps: LocaleActionDeps = {}): Promise<void> => {
  const repoRoot = deps.repoRoot ?? process.cwd();

  if (args.generate) {
    doGenerate(repoRoot);
  } else if (args.validate) {
    if (!doValidate(repoRoot)) {
      throw new Error("Locale validation failed — see errors above");
    }
    console.error("All locale files are valid.");
  }
};
