import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { LocaleFileSchema } from "../src/utils/locale-schema";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "..");

const localesDir = path.resolve(repoRoot, "locales");
const localeFiles = fs
  .readdirSync(localesDir)
  .filter((f) => f.endsWith(".json"))
  .sort();

const generateSchema = () => {
  const schema = LocaleFileSchema.toJSONSchema();
  const outPath = path.resolve(repoRoot, "locale-schema.json");
  fs.writeFileSync(outPath, JSON.stringify(schema, null, 2) + "\n");
  console.error(`Generated locale-schema.json at ${outPath}`);
};

const generateLocaleType = () => {
  const codes = localeFiles.map((f) => path.basename(f, ".json"));
  const union = codes.map((c) => `  | "${c}"`).join("\n");
  const content = `// Auto-generated by scripts/generate-locale-schema.ts — do not edit manually
// Run \`bun run validate:schema\` to regenerate from locales/ directory.

export type Locale =
${union};
`;
  const outPath = path.resolve(repoRoot, "src/types/locale.ts");
  fs.writeFileSync(outPath, content);
  console.error(`Generated src/types/locale.ts (${codes.length} locales)`);
};

generateSchema();
generateLocaleType();
